jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ./app/keystore.jks

    - name: Grant execution permission to gradlew
      run: chmod +x ./gradlew

    - name: Build Signed Release APK
      run: |
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=app/keystore.jks \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASSWORD \
          --stacktrace --info

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
        retention-days: 30
